name: czestny_check
description: Minimal Flutter web scaffold for HonestCheck
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
