name: Web Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, linux, aidomio ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Fix flutter git safe.directory
        shell: bash
        run: |
          set -e
          FLUTTER_DIR=/opt/hostedtoolcache/flutter
          # если sudo есть — поправим владельца, иначе пропустим
          if command -v sudo >/dev/null 2>&1; then
            sudo chown -R "$USER":"$USER" "$FLUTTER_DIR" || true
          fi
          # добавим все версии Flutter в safe.directory (не ругается, если уже есть)
          if [ -d "$FLUTTER_DIR" ]; then
            git config --global --add safe.directory "$FLUTTER_DIR" || true
            for d in "$FLUTTER_DIR"/*-x64; do
              [ -d "$d" ] && git config --global --add safe.directory "$d" || true
            done
          fi

      - name: Flutter doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Get deps
        run: flutter pub get
        working-directory: .

      - name: Build web (release)
        run: flutter build web --release --no-tree-shake-icons
        working-directory: .

      - name: Deploy to /srv/cc_web
        shell: bash
        run: |
          rm -rf /srv/cc_web/*
          cp -r build/web/* /srv/cc_web/
          echo "Deployed at $(date -Is)" > /srv/cc_web/DEPLOYED.txt
        working-directory: .
